global using System.Text.Json;
global using CRM.Identity.Api.Common.Middlewares;
global using CRM.Identity.Api.Controllers.Base;
global using CRM.Identity.Application.Common.Abstractions;
global using CRM.Identity.Application.DI;
global using CRM.Identity.Domain.Common.Models;
global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using Scalar.AspNetCore;
